services:
  k3s:
    container_name: k3s-local
    image: docker.io/rancher/k3s:v1.29.4-k3s1
    privileged: true
    command:
      - server
      - --disable=servicelb,traefik,local-storage,metrics-server
      - --kube-apiserver-arg=etcd-compaction-interval=10s
      - --disable-network-policy
      - --flannel-iface=eth0
    environment:
      K3S_DATASTORE_ENDPOINT: "http://host.lima.internal:2379"
    volumes:
      - kubeconfig-local:/etc/rancher/k3s

volumes:
  kubeconfig-local:
    name: kubeconfig-local
