apiVersion: apps/v1
kind: Deployment
metadata:
  name: f8n
  namespace: fdb
  labels:
    app: f8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f8n
  template:
    metadata:
      labels:
        app: f8n
    spec:
      containers:
        - name: f8n
          image: fra.vultrcr.com/f8ntest/f8n:0.7.0
          command: ["/bin/f8n", "--debug"]
          volumeMounts:
            - name: fdb-cluster-volume
              mountPath: /etc/foundationdb/fdb.cluster
              subPath: fdb.cluster
      volumes:
        - name: fdb-cluster-volume
          configMap:
            name: fdb-cluster-file
---
apiVersion: v1
kind: Service
metadata:
  name: f8n
  namespace: fdb
spec:
  selector:
    app: f8n
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
