apiVersion: v1
kind: Namespace
metadata:
  name: fdb
---
apiVersion: v1
kind: Service
metadata:
  name: fdb
  namespace: fdb
spec:
  ipFamilyPolicy: PreferDualStack
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: fdb
  ports:
    - port: 4500
      name: fdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fdb
  namespace: fdb
spec:
  volumeClaimTemplates:
    - metadata:
        name: fdb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: openebs-hostpath
#        storageClassName: nvme-ssd-block
        resources:
          requests:
            storage: 150Gi
    - metadata:
        name: fdb-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: openebs-hostpath
#        storageClassName: nvme-ssd-block
        resources:
          requests:
            storage: 150Gi
  replicas: 1
  selector:
    matchLabels:
      app: fdb
  serviceName: fdb
  template:
    metadata:
      labels:
        app: fdb
    spec:
      volumes:
        - name: fdb-cluster-volume
          emptyDir: {}
      containers:
        - name: fdb
          image: ghcr.io/melgenek/f8n/foundationdb:7.3.69
          resources:
            requests:
              cpu: 4
              memory: 5
          env:
            - name: FDB_CLUSTER_FILE
              value: /opt/fdb-cluster/fdb.cluster
          volumeMounts:
            - name: fdb-cluster-volume
              mountPath: /opt/fdb-cluster
              readOnly: false
            - name: fdb-data
              mountPath: /opt/foundationdb-data
              readOnly: false
            - name: fdb-logs
              mountPath: /opt/foundationdb-logs
              readOnly: false
          command: ["/bin/bash"]
          args:
            - "-c"
            # Fixing the https://github.com/apple/foundationdb/blob/release-7.3/packaging/docker/fdb.bash for IPv6
            - >
              raw_ip=$(hostname -i | awk '{print $1}');
              if [[ "$raw_ip" == *:* ]]; then
                # If it's IPv6, wrap it in brackets.
                public_ip="[$raw_ip]";
              else
                # Otherwise, return it as is (IPv4).
                public_ip="$raw_ip";
              fi;

              echo "export PUBLIC_IP=$public_ip" > /var/fdb/.fdbenv;
              source /var/fdb/.fdbenv;
              echo "docker:docker@$PUBLIC_IP:4500" > "$FDB_CLUSTER_FILE";
              
              echo "Starting FDB server on $PUBLIC_IP:$FDB_PORT";
              fdbserver --listen-address "$PUBLIC_IP:$FDB_PORT" --public-address "$PUBLIC_IP:$FDB_PORT" \
                  --datadir /opt/foundationdb-data --logdir /opt/foundationdb-logs \
                  --locality-zoneid="$(hostname)" --locality-machineid="$(hostname)" --class "$FDB_PROCESS_CLASS"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - >
                    while [ ! -f  /opt/fdb-cluster/fdb.cluster ]; do
                      sleep 0.1;
                    done;
                    if ! fdbcli --exec status --timeout 3 ; then
                      echo "creating the database";
                      if ! fdbcli --exec "configure new single ssd-redwood-1 ; status" --timeout 10 ; then
                          echo "Unable to configure new FDB cluster.";
                          exit 1;
                      elif ! fdbcli --exec "configure single ssd-redwood-1 ; status" --timeout 10 ; then
                          echo "Unable to configure existing FDB cluster.";
                          exit 1;
                      fi
                    fi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fdb-cluster-file
  namespace: fdb
data:
  fdb.cluster: "docker:docker@fdb:4500"
