openebs-crds:
  csi:
    volumeSnapshots:
      enabled: false

engines:
  local:
    lvm:
      enabled: true
    zfs:
      enabled: false
    rawfile:
      enabled: false
  replicated:
    mayastor:
      enabled: false

loki:
  enabled: false

alloy:
  enabled: false

minio:
  enabled: false
