apiVersion: v1
kind: Namespace
metadata:
  name: etcd-lease-flood
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-lease-flood
  namespace: etcd-lease-flood
  labels:
    app: etcd-lease-flood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-lease-flood
  template:
    metadata:
      labels:
        app: etcd-lease-flood
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fdb
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: etcd-lease-flood
          image: fra.vultrcr.com/f8ntest/lease-flood:0.0.4
          command: ["/etcd-lease-flood"]
          args: [
            "--endpoints=f8n.fdb:2379",
            "--workers=100",
            "--num-keys=1000"
          ]
          resources:
            requests:
              cpu: 1
