apiVersion: v1
kind: Namespace
metadata:
  name: etcd-benchmark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-benchmark
  namespace: etcd-benchmark
  labels:
    app: etcd-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-benchmark
  template:
    metadata:
      labels:
        app: etcd-benchmark
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fdb
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: etcd-benchmark
          image: fra.vultrcr.com/f8ntest/etcd-benchmark:0.0.1
          command: ["/benchmark"]
          args: [
            "--endpoints=f8n.fdb:2379",
            "put",
            "--key-size=48",
            "--val-size=1024",
            "--total=10000000",
            "--conns=10",
            "--clients=100" # 1000
          ]
          resources:
            requests:
              cpu: 3
