apiVersion: v1
kind: ServiceAccount
metadata:
  name: fdb-kubernetes
  namespace: fdb-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fdb-kubernetes
  namespace: fdb-operator
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "update"
      - "patch"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fdb-kubernetes
  namespace: fdb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fdb-kubernetes
subjects:
  - kind: ServiceAccount
    name: fdb-kubernetes
---
apiVersion: apps.foundationdb.org/v1beta2
kind: FoundationDBCluster
metadata:
  namespace: fdb-operator
  name: test-cluster
spec:
  automationOptions:
    replacements:
      enabled: true
  faultDomain:
    key: foundationdb.org/none
  imageType: unified
  labels:
    matchLabels:
      foundationdb.org/fdb-cluster-name: test-cluster
    processClassLabels:
      - foundationdb.org/fdb-process-class
    processGroupIDLabels:
      - foundationdb.org/fdb-process-group-id
  minimumUptimeSecondsForBounce: 60
  processCounts:
    cluster_controller: 1
    stateless: -1
  processes:
    general:
      podTemplate:
        spec:
          serviceAccount: fdb-kubernetes
#          nodeSelector:
#            vke.vultr.com/node-pool: fdb-pool
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  foundationdb.org/fdb-cluster-name: test-cluster
          containers:
            - name: foundationdb
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
              securityContext:
                runAsUser: 0
            - name: foundationdb-kubernetes-sidecar
              resources:
                requests:
                  cpu: 25m
                  memory: 128Mi
              securityContext:
                runAsUser: 0
          initContainers: []
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          resources:
            requests:
              storage: 8G
  routing:
    useDNSInClusterFile: true
  sidecarContainer:
    enableLivenessProbe: true
    enableReadinessProbe: false
  version: 7.3.63
  databaseConfiguration:
    redundancy_mode: double
    storage_engine: ssd-redwood-1
