apiVersion: apps/v1
kind: Deployment
metadata:
  name: f8n
  namespace: fdb
  labels:
    app: f8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f8n
  template:
    metadata:
      labels:
        app: f8n
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: foundationdb.org/fdb-cluster-name
                operator: In
                values:
                - test-cluster
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: f8n
          image: fra.vultrcr.com/f8ntest/f8n:0.16.0
          resources:
            requests:
              cpu: 3
            limits:
              memory: 2Gi
          env:
            # https://goperf.dev/01-common-patterns/gc/#gc-tuning-gogc
            - name: GOGC
              value: "500"
            # https://github.com/bchess/k8s-1m/tree/main?tab=readme-ov-file#garbage-collection
            - name: GOMEMLIMIT
              value: "1700MiB"
          command: ["/bin/f8n", "--fdb-clean-directory-on-start", "--metrics-enable-profiling"]
          volumeMounts:
            - name: fdb-cluster-volume
              mountPath: /etc/foundationdb/fdb.cluster
              subPath: cluster-file
      volumes:
        - name: fdb-cluster-volume
          configMap:
            name: test-cluster-config
---
apiVersion: v1
kind: Service
metadata:
  name: f8n
  namespace: fdb
  labels:
    app: f8n
spec:
  selector:
    app: f8n
  ports:
    - name: etcd
      protocol: TCP
      port: 2379
      targetPort: 2379
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: f8n
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: f8n
  namespaceSelector:
    matchNames:
      - fdb
  endpoints:
    - port: metrics
      interval: 10s
