services:
  fdb-demo:
    container_name: fdb-demo
    image: ghcr.io/melgenek/f8n/foundationdb:7.3.69
    post_start:
     - command: >
        bash -c '
          while [ ! -f /var/fdb/fdb.cluster ]; do
            sleep 0.1
          done
          if ! fdbcli --exec status --timeout 3 ; then
            echo "creating the database"
            if ! fdbcli --exec "configure new single ssd ; status" --timeout 10 ; then
                echo "Unable to configure new FDB cluster."
                exit 1
            elif ! fdbcli --exec "configure single ssd ; status" --timeout 10 ; then
                echo "Unable to configure existing FDB cluster."
                exit 1
            fi
          fi
        '
  f8n-demo:
    container_name: f8n-demo
    image: ghcr.io/melgenek/f8n:v0.2.0
    volumes:
      - ./fdb.cluster:/etc/foundationdb/fdb.cluster:ro
  k3s-demo:
    container_name: k3s-demo
    depends_on:
      - f8n-demo
    image: docker.io/rancher/k3s:v1.33.3-k3s1
    privileged: true
    command:
      - server
      - --kube-apiserver-arg=etcd-compaction-interval=10s
      - --disable=coredns,servicelb,traefik,local-storage,metrics-server
      - --kube-apiserver-arg=feature-gates=WatchList=true
      - --disable-network-policy
    environment:
      K3S_DATASTORE_ENDPOINT: "http://f8n-demo:2379"
