#!/bin/bash
set -e

cd $(dirname $0)/..

. ./scripts/test-helpers

# ---

docker ps

# ---

if [ -n "$1" ]; then
    . ./scripts/test-run-"$1"
    echo "Did test-run-$1 $?"
    exit 0
else
    echo "Run test <driver> $?"
    exit 1
fi

exit 0
