name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Start K3S
        run: make start-k3s

      - name: Run conformance tests
        run: make test-conformance

      - name: Run flaky conformance tests
        run: make test-conformance-flaky || true

      - name: Store logs
        if: always()
        run: |
          mkdir output
          docker logs f8n > output/f8n-logs.txt || true
          docker logs k3s > output/k3s-logs.txt || true

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-results
          path: output/
